# Generated by Django 6.0.3 on 2026-06-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255, unique=True)),
                ('conteudo', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo de Mídia',
                'verbose_name_plural': 'Arquivos de Mídia',
                'db_table': 'arquivos_midia',
            },
        ),
    ]
