# Generated by Django 6.0.3 on 2026-06-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_arquivomidia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('achado', 'Achado'), ('perdido', 'Perdido'), ('devolvido', 'Devolvido'), ('pendente_confirmacao', 'Pendente de Confirmação'), ('confirmado', 'Confirmado no Balcão')], max_length=45),
        ),
    ]
