# Generated by Django 6.0.3 on 2026-06-18 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('confirmou', 'Confirmou item no balcão'), ('devolveu', 'Registrou devolução'), ('editou', 'Editou item'), ('status_alterado', 'Alterou status')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('bolsista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_log', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='items.item')),
            ],
            options={
                'db_table': 'find_acaolog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
