# Generated by Django 6.0 on 2026-01-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/user.png', upload_to='profile_pics'),
        ),
    ]
