# Generated by Django 5.2 on 2026-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('fechado', 'Fechado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem')], default='texto', max_length=20),
        ),
    ]
