# Generated by Django 6.0 on 2026-01-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_chat_criado_por_alter_chat_dono_item_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_chat_por_item_e_usuarios',
        ),
        migrations.AlterField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='mainpage.item'),
        ),
    ]
