# Generated by Django 6.0 on 2026-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_categoria_chat_item_mensagem_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('achado', 'Achado'), ('devolvido', 'devolvido'), ('perdido', 'Perdido')], max_length=45),
        ),
    ]
