# Generated by Django 6.0 on 2026-01-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_categoria_descricao_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('achado', 'Achado'), ('devolvido', 'devolvido')], max_length=45),
        ),
    ]
